# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e221be84a83393c6f7541d74bc3e8157872d2ca187823d5b0efb266fbb84e3d5758461c424fead72cef6cba15bc3d5be831d83937749cefeed338180bbca3f

test:
  secret_key_base: 00b2547cce95bb9340b74cb85461f114410a2207a1d7a0b2428b0f4742c1cec861abaefd122bd7d7a9cb3e4633e88c47ad95aedbde0f3aace931be4842ef04a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
